FROM node:18-alpine AS build

WORKDIR /app
COPY . .
RUN npm i
RUN npm run build

FROM node:18-alpine AS server

WORKDIR /app
RUN rm -rf ./*
COPY --from=build /app/package.json .
COPY --from=build /app/build .
RUN npm i --omit=dev

ENV ORIGIN=http://localhost

CMD ["node", "index.js"]